const FETCH_TASKS_MENU_REQUEST = 'FETCH_TASKS_MENU_REQUEST';
const FETCH_TASKS_MENU_SUCCESS = 'FETCH_TASKS_MENU_SUCCESS';
const FETCH_TASKS_MENU_FAIL = 'FETCH_TASKS_MENU_FAIL';
const FILTER_TASKS_MENU = 'FILTER_TASKS_MENU';

export default {
  FETCH_TASKS_MENU_REQUEST,
  FETCH_TASKS_MENU_SUCCESS,
  FETCH_TASKS_MENU_FAIL,
  FILTER_TASKS_MENU,
};
