const FETCH_DEPLOYMENT_RUNS_REQUEST = 'FETCH_DEPLOYMENT_RUNS_REQUEST';
const CREATE_DEPLOYMENT_RUN_REQUEST = 'CREATE_DEPLOYMENT_RUN_REQUEST';
const DELETE_DEPLOYMENT_RUN_REQUEST = 'DELETE_DEPLOYMENT_RUN_REQUEST';
const RETRY_DEPLOYMENT_RUN_REQUEST = 'RETRY_DEPLOYMENT_RUN_REQUEST';

const FETCH_DEPLOYMENT_RUNS_SUCCESS = 'FETCH_DEPLOYMENT_RUNS_SUCCESS';
const CREATE_DEPLOYMENT_RUN_SUCCESS = 'CREATE_DEPLOYMENT_RUN_SUCCESS';
const DELETE_DEPLOYMENT_RUN_SUCCESS = 'DELETE_DEPLOYMENT_RUN_SUCCESS';
const RETRY_DEPLOYMENT_RUN_SUCCESS = 'RETRY_DEPLOYMENT_RUN_SUCCESS';

const FETCH_DEPLOYMENT_RUNS_FAIL = 'FETCH_DEPLOYMENT_RUNS_FAIL';
const CREATE_DEPLOYMENT_RUN_FAIL = 'CREATE_DEPLOYMENT_RUN_FAIL';
const DELETE_DEPLOYMENT_RUN_FAIL = 'DELETE_DEPLOYMENT_RUN_FAIL';
const RETRY_DEPLOYMENT_RUN_FAIL = 'RETRY_DEPLOYMENT_RUN_FAIL';

export default {
  FETCH_DEPLOYMENT_RUNS_REQUEST,
  CREATE_DEPLOYMENT_RUN_REQUEST,
  DELETE_DEPLOYMENT_RUN_REQUEST,
  RETRY_DEPLOYMENT_RUN_REQUEST,

  FETCH_DEPLOYMENT_RUNS_SUCCESS,
  CREATE_DEPLOYMENT_RUN_SUCCESS,
  DELETE_DEPLOYMENT_RUN_SUCCESS,
  RETRY_DEPLOYMENT_RUN_SUCCESS,

  FETCH_DEPLOYMENT_RUNS_FAIL,
  CREATE_DEPLOYMENT_RUN_FAIL,
  DELETE_DEPLOYMENT_RUN_FAIL,
  RETRY_DEPLOYMENT_RUN_FAIL,
};
