// ACTION TYPES
// REQUEST
// fetch deployment runs request
const FETCH_DEPLOYMENT_RUNS_REQUEST = 'FETCH_DEPLOYMENT_RUNS_REQUEST';
// create deployment run request
const CREATE_DEPLOYMENT_RUN_REQUEST = 'CREATE_DEPLOYMENT_RUN_REQUEST';
// delete deployment run request
const DELETE_DEPLOYMENT_RUN_REQUEST = 'DELETE_DEPLOYMENT_RUN_REQUEST';
// retry deployment run request
const RETRY_DEPLOYMENT_RUN_REQUEST = 'RETRY_DEPLOYMENT_RUN_REQUEST';

// SUCCESS
// fetch deployment runs success
const FETCH_DEPLOYMENT_RUNS_SUCCESS = 'FETCH_DEPLOYMENT_RUNS_SUCCESS';
// create deployment run success
const CREATE_DEPLOYMENT_RUN_SUCCESS = 'CREATE_DEPLOYMENT_RUN_SUCCESS';
// delete deployment run success
const DELETE_DEPLOYMENT_RUN_SUCCESS = 'DELETE_DEPLOYMENT_RUN_SUCCESS';
// retry deployment run success
const RETRY_DEPLOYMENT_RUN_SUCCESS = 'RETRY_DEPLOYMENT_RUN_SUCCESS';

// FAIL
// fetch deployment runs fail
const FETCH_DEPLOYMENT_RUNS_FAIL = 'FETCH_DEPLOYMENT_RUNS_FAIL';
// create deployment run fail
const CREATE_DEPLOYMENT_RUN_FAIL = 'CREATE_DEPLOYMENT_RUN_FAIL';
// delete deployment run fail
const DELETE_DEPLOYMENT_RUN_FAIL = 'DELETE_DEPLOYMENT_RUN_FAIL';
// retry deployment run fail
const RETRY_DEPLOYMENT_RUN_FAIL = 'RETRY_DEPLOYMENT_RUN_FAIL';

// EXPORT
export default {
  // REQUEST
  FETCH_DEPLOYMENT_RUNS_REQUEST,
  CREATE_DEPLOYMENT_RUN_REQUEST,
  DELETE_DEPLOYMENT_RUN_REQUEST,
  RETRY_DEPLOYMENT_RUN_REQUEST,

  // SUCCESS
  FETCH_DEPLOYMENT_RUNS_SUCCESS,
  CREATE_DEPLOYMENT_RUN_SUCCESS,
  DELETE_DEPLOYMENT_RUN_SUCCESS,
  RETRY_DEPLOYMENT_RUN_SUCCESS,

  // FAIL
  FETCH_DEPLOYMENT_RUNS_FAIL,
  CREATE_DEPLOYMENT_RUN_FAIL,
  DELETE_DEPLOYMENT_RUN_FAIL,
  RETRY_DEPLOYMENT_RUN_FAIL
}