// ACTION TYPES
const DELETE_DEPLOYED_EXPERIMENT = 'DELETE_DEPLOYED_EXPERIMENT';
const DELETE_DEPLOYED_EXPERIMENT_FAIL = 'DELETE_DEPLOYED_EXPERIMENT_FAIL';
const DELETE_DEPLOYED_EXPERIMENT_REQUEST = 'DELETE_DEPLOYED_EXPERIMENT_REQUEST';

const FETCH_DEPLOYED_EXPERIMENTS = 'FETCH_DEPLOYED_EXPERIMENTS';
const FETCH_DEPLOYED_EXPERIMENTS_FAIL = 'FETCH_DEPLOYED_EXPERIMENTS_FAIL';
const FETCH_DEPLOYED_EXPERIMENTS_REQUEST = 'FETCH_DEPLOYED_EXPERIMENTS_REQUEST';

// EXPORT
export default {
  DELETE_DEPLOYED_EXPERIMENT,
  DELETE_DEPLOYED_EXPERIMENT_FAIL,
  DELETE_DEPLOYED_EXPERIMENT_REQUEST,
  FETCH_DEPLOYED_EXPERIMENTS,
  FETCH_DEPLOYED_EXPERIMENTS_FAIL,
  FETCH_DEPLOYED_EXPERIMENTS_REQUEST,
};
