// ACTION TYPES
const DELETE_DEPLOYED_EXPERIMENT_SUCCESS = 'DELETE_DEPLOYED_EXPERIMENT_SUCCESS';
const DELETE_DEPLOYED_EXPERIMENT_FAIL = 'DELETE_DEPLOYED_EXPERIMENT_FAIL';
const DELETE_DEPLOYED_EXPERIMENT_REQUEST = 'DELETE_DEPLOYED_EXPERIMENT_REQUEST';

const FETCH_DEPLOYED_EXPERIMENTS_SUCCESS = 'FETCH_DEPLOYED_EXPERIMENTS_SUCCESS';
const FETCH_DEPLOYED_EXPERIMENTS_FAIL = 'FETCH_DEPLOYED_EXPERIMENTS_FAIL';
const FETCH_DEPLOYED_EXPERIMENTS_REQUEST = 'FETCH_DEPLOYED_EXPERIMENTS_REQUEST';

// EXPORT
export default {
  DELETE_DEPLOYED_EXPERIMENT_SUCCESS,
  DELETE_DEPLOYED_EXPERIMENT_FAIL,
  DELETE_DEPLOYED_EXPERIMENT_REQUEST,
  FETCH_DEPLOYED_EXPERIMENTS_SUCCESS,
  FETCH_DEPLOYED_EXPERIMENTS_FAIL,
  FETCH_DEPLOYED_EXPERIMENTS_REQUEST,
};
