// ACTION TYPES
const DELETE_DEPLOYED_EXPERIMENT = 'DELETE_DEPLOYED_EXPERIMENT';
const DELETE_DEPLOYED_EXPERIMENT_FAIL = 'DELETE_DEPLOYED_EXPERIMENT_FAIL';
const DELETE_DEPLOYED_EXPERIMENT_REQUEST = 'DELETE_DEPLOYED_EXPERIMENT_REQUEST';

const FETCH_DEPLOYED_EXPERIMENTS = 'FETCH_DEPLOYED_EXPERIMENTS';
const FETCH_DEPLOYED_EXPERIMENTS_FAIL = 'FETCH_DEPLOYED_EXPERIMENTS_FAIL';
const FETCH_DEPLOYED_EXPERIMENTS_REQUEST = 'FETCH_DEPLOYED_EXPERIMENTS_REQUEST';

const FETCH_DEPLOYMENTS_REQUEST = 'FETCH_DEPLOYMENTS_REQUEST';
const FETCH_DEPLOYMENTS_SUCCESS = 'FETCH_DEPLOYMENTS_SUCCESS';
const FETCH_DEPLOYMENTS_FAIL = 'FETCH_DEPLOYMENTS_FAIL';

const CREATE_DEPLOYMENT_REQUEST = 'CREATE_DEPLOYMENT_REQUEST';
const CREATE_DEPLOYMENT_SUCCESS = 'CREATE_DEPLOYMENT_SUCCESS';
const CREATE_DEPLOYMENT_FAIL = 'CREATE_DEPLOYMENT_FAIL';

const DELETE_DEPLOYMENT_REQUEST = 'DELETE_DEPLOYMENT_REQUEST';
const DELETE_DEPLOYMENT_SUCCESS = 'DELETE_DEPLOYMENT_SUCCESS ';
const DELETE_DEPLOYMENT_FAIL = 'DELETE_DEPLOYMENT_FAIL';

const UPDATE_DEPLOYMENT_REQUEST = 'UPDATE_DEPLOYMENT_REQUEST';
const UPDATE_DEPLOYMENT_SUCCESS = 'UPDATE_DEPLOYMENT_SUCCESS';
const UPDATE_DEPLOYMENT_FAIL = 'UPDATE_DEPLOYMENT_FAIL';

// EXPORT
export default {
  DELETE_DEPLOYED_EXPERIMENT,
  DELETE_DEPLOYED_EXPERIMENT_FAIL,
  DELETE_DEPLOYED_EXPERIMENT_REQUEST,
  FETCH_DEPLOYED_EXPERIMENTS,
  FETCH_DEPLOYED_EXPERIMENTS_FAIL,
  FETCH_DEPLOYED_EXPERIMENTS_REQUEST,

  FETCH_DEPLOYMENTS_REQUEST,
  FETCH_DEPLOYMENTS_SUCCESS,
  FETCH_DEPLOYMENTS_FAIL,

  CREATE_DEPLOYMENT_REQUEST,
  CREATE_DEPLOYMENT_SUCCESS,
  CREATE_DEPLOYMENT_FAIL,

  DELETE_DEPLOYMENT_REQUEST,
  DELETE_DEPLOYMENT_SUCCESS,
  DELETE_DEPLOYMENT_FAIL,

  UPDATE_DEPLOYMENT_REQUEST,
  UPDATE_DEPLOYMENT_SUCCESS,
  UPDATE_DEPLOYMENT_FAIL,
};
