// ACTION TYPES
// REQUEST
// fetch components menu request
const FETCH_COMPONENTS_MENU_REQUEST = 'FETCH_COMPONENTS_MENU_REQUEST';

// SUCCESS
// fetch components menu success
const FETCH_COMPONENTS_MENU_SUCCESS = 'FETCH_COMPONENTS_MENU_SUCCESS';

// FAIL
// fetch components menu fail
const FETCH_COMPONENTS_MENU_FAIL = 'FETCH_COMPONENTS_MENU_FAIL';

// COMMON
// filter components menu
const FILTER_COMPONENTS_MENU = 'FILTER_COMPONENTS_MENU';

// EXPORT
export default {
  // REQUEST
  FETCH_COMPONENTS_MENU_REQUEST,

  // SUCCESS
  FETCH_COMPONENTS_MENU_SUCCESS,

  // FAIL
  FETCH_COMPONENTS_MENU_FAIL,

  // COMMON
  FILTER_COMPONENTS_MENU,
};
