// ACTION TYPES
const CREATE_DEPLOYMENT_REQUEST = 'CREATE_DEPLOYMENT_REQUEST';
const CREATE_DEPLOYMENT_SUCCESS = 'CREATE_DEPLOYMENT_SUCCESS';
const CREATE_DEPLOYMENT_FAILURE = 'CREATE_DEPLOYMENT_FAILURE';

const DELETE_DEPLOYMENT_REQUEST = 'DELETE_DEPLOYMENT_REQUEST';
const DELETE_DEPLOYMENT_SUCCESS = 'DELETE_DEPLOYMENT_SUCCESS';
const DELETE_DEPLOYMENT_FAILURE = 'DELETE_DEPLOYMENT_FAILURE';

const FETCH_DEPLOYMENT_REQUEST = 'FETCH_DEPLOYMENT_REQUEST';
const FETCH_DEPLOYMENT_SUCCESS = 'FETCH_DEPLOYMENT_SUCCESS';
const FETCH_DEPLOYMENT_FAILURE = 'FETCH_DEPLOYMENT_FAILURE';

const UPDATE_DEPLOYMENT_POSITION_REQUEST = 'UPDATE_DEPLOYMENT_POSITION_REQUEST';
const UPDATE_DEPLOYMENT_POSITION_SUCCESS = 'UPDATE_DEPLOYMENT_POSITION_SUCCESS';
const UPDATE_DEPLOYMENT_POSITION_FAILURE = 'UPDATE_DEPLOYMENT_POSITION_FAILURE';

// EXPORT
export default {
  CREATE_DEPLOYMENT_REQUEST,
  CREATE_DEPLOYMENT_SUCCESS,
  CREATE_DEPLOYMENT_FAILURE,
  DELETE_DEPLOYMENT_REQUEST,
  DELETE_DEPLOYMENT_SUCCESS,
  DELETE_DEPLOYMENT_FAILURE,
  FETCH_DEPLOYMENT_REQUEST,
  FETCH_DEPLOYMENT_SUCCESS,
  FETCH_DEPLOYMENT_FAILURE,
  UPDATE_DEPLOYMENT_POSITION_REQUEST,
  UPDATE_DEPLOYMENT_POSITION_SUCCESS,
  UPDATE_DEPLOYMENT_POSITION_FAILURE,
};
