// ACTION TYPES
const ADD_COMPARE_RESULT = 'ADD_COMPARE_RESULT';
const DELETE_COMPARE_RESULT = 'DELETE_COMPARE_RESULT';
const FETCH_COMPARE_RESULTS = 'FETCH_COMPARE_RESULTS';
const FETCH_EXPERIMENTS_TRAINING_HISTORY = 'FETCH_EXPERIMENTS_TRAINING_HISTORY';
const UPDATE_COMPARE_RESULT = 'UPDATE_COMPARE_RESULT';
const UPDATE_EXPERIMENTS_OPTIONS = 'UPDATE_EXPERIMENTS_OPTIONS';

// EXPORT
export default {
  ADD_COMPARE_RESULT,
  DELETE_COMPARE_RESULT,
  FETCH_COMPARE_RESULTS,
  FETCH_EXPERIMENTS_TRAINING_HISTORY,
  UPDATE_COMPARE_RESULT,
  UPDATE_EXPERIMENTS_OPTIONS,
};
