// ACTION TYPES
const ADD_COMPARE_RESULT_REQUEST = 'ADD_COMPARE_RESULT_REQUEST';
const ADD_COMPARE_RESULT_SUCCESS = 'ADD_COMPARE_RESULT_SUCCESS';
const ADD_COMPARE_RESULT_FAIL = 'ADD_COMPARE_RESULT_FAIL';

const DELETE_COMPARE_RESULT_REQUEST = 'DELETE_COMPARE_RESULT_REQUEST';
const DELETE_COMPARE_RESULT_SUCCESS = 'DELETE_COMPARE_RESULT_SUCCESS';
const DELETE_COMPARE_RESULT_FAIL = 'DELETE_COMPARE_RESULT_FAIL';


const FETCH_COMPARE_RESULTS_REQUEST = 'FETCH_COMPARE_RESULTS_REQUEST';
const FETCH_COMPARE_RESULTS_SUCCESS = 'FETCH_COMPARE_RESULTS_SUCCESS';
const FETCH_COMPARE_RESULTS_FAIL = 'FETCH_COMPARE_RESULTS_FAIL';


const FETCH_EXPERIMENTS_TRAINING_RESULT_REQUEST = 'FETCH_EXPERIMENTS_TRAINING_RESULT_REQUEST';
const FETCH_EXPERIMENTS_TRAINING_RESULT_SUCCESS = 'FETCH_EXPERIMENTS_TRAINING_RESULT_SUCCESS';
const FETCH_EXPERIMENTS_TRAINING_RESULT_FAIL = 'FETCH_EXPERIMENTS_TRAINING_RESULT_FAIL';

const UPDATE_COMPARE_RESULT_REQUEST = 'UPDATE_COMPARE_RESULT_REQUEST';

const UPDATE_EXPERIMENTS_OPTIONS_REQUEST = 'UPDATE_EXPERIMENTS_OPTIONS_REQUEST';



// EXPORT
export default {

  // Add compare
  ADD_COMPARE_RESULT_REQUEST,
  ADD_COMPARE_RESULT_SUCCESS,
  ADD_COMPARE_RESULT_FAIL,

  // Delete compare
  DELETE_COMPARE_RESULT_REQUEST,
  DELETE_COMPARE_RESULT_SUCCESS,
  DELETE_COMPARE_RESULT_FAIL,

  // Fetch compare result
  FETCH_COMPARE_RESULTS_REQUEST,
  FETCH_COMPARE_RESULTS_SUCCESS,
  FETCH_COMPARE_RESULTS_FAIL,

  // Fetch experiments training history
  FETCH_EXPERIMENTS_TRAINING_RESULT_REQUEST,
  FETCH_EXPERIMENTS_TRAINING_RESULT_SUCCESS,
  FETCH_EXPERIMENTS_TRAINING_RESULT_FAIL,

  // Update compare result
  UPDATE_COMPARE_RESULT_REQUEST,

  // Update experiments options
  UPDATE_EXPERIMENTS_OPTIONS_REQUEST,
};