// ACTION TYPES
// REQUEST
// train experiment request
const TRAIN_EXPERIMENT_REQUEST = 'TRAIN_EXPERIMENT_REQUEST';
// get train experiment status request
const GET_TRAIN_EXPERIMENT_STATUS_REQUEST =
  'GET_TRAIN_EXPERIMENT_STATUS_REQUEST';
// deploy experiment request
const CREATE_DEPLOYMENT_REQUEST = 'CREATE_DEPLOYMENT_REQUEST';

// SUCCESS
// train experiment success
const TRAIN_EXPERIMENT_SUCCESS = 'TRAIN_EXPERIMENT_SUCCESS';
// get train experiment status success
const GET_TRAIN_EXPERIMENT_STATUS_SUCCESS =
  'GET_TRAIN_EXPERIMENT_STATUS_SUCCESS';
// create deploy experiment success
const CREATE_DEPLOYMENT_SUCCESS = 'CREATE_DEPLOYMENT_SUCCESS';

// FAIL
// train experiment fail
const TRAIN_EXPERIMENT_FAIL = 'TRAIN_EXPERIMENT_FAIL';
// get train experiment status fail
const GET_TRAIN_EXPERIMENT_STATUS_FAIL = 'GET_TRAIN_EXPERIMENT_STATUS_FAIL';
// deploy experiment fail
const CREATE_DEPLOYMENT_FAIL = 'CREATE_DEPLOYMENT_FAIL';

// EXPORT
export default {
  // REQUEST
  TRAIN_EXPERIMENT_REQUEST,
  GET_TRAIN_EXPERIMENT_STATUS_REQUEST,
  CREATE_DEPLOYMENT_REQUEST,

  // SUCCESS
  TRAIN_EXPERIMENT_SUCCESS,
  GET_TRAIN_EXPERIMENT_STATUS_SUCCESS,
  CREATE_DEPLOYMENT_SUCCESS,

  // FAIL
  TRAIN_EXPERIMENT_FAIL,
  GET_TRAIN_EXPERIMENT_STATUS_FAIL,
  CREATE_DEPLOYMENT_FAIL,
};
