// ACTION TYPES
// REQUEST
// create experiment run request
const CREATE_EXPERIMENT_RUN_REQUEST = 'CREATE_EXPERIMENT_RUN_REQUEST';
// get train experiment status request
const GET_TRAIN_EXPERIMENT_STATUS_REQUEST =
  'GET_TRAIN_EXPERIMENT_STATUS_REQUEST';
// deploy experiment request
const CREATE_DEPLOYMENT_REQUEST = 'CREATE_DEPLOYMENT_REQUEST';

// SUCCESS
// create experiment run success
const CREATE_EXPERIMENT_RUN_SUCCESS = 'CREATE_EXPERIMENT_RUN_SUCCESS';
// get train experiment status success
const GET_TRAIN_EXPERIMENT_STATUS_SUCCESS =
  'GET_TRAIN_EXPERIMENT_STATUS_SUCCESS';
// create deploy experiment success
const CREATE_DEPLOYMENT_SUCCESS = 'CREATE_DEPLOYMENT_SUCCESS';

// FAIL
// create experiment run fail
const CREATE_EXPERIMENT_RUN_FAIL = 'CREATE_EXPERIMENT_RUN_FAIL';
// get train experiment status fail
const GET_TRAIN_EXPERIMENT_STATUS_FAIL = 'GET_TRAIN_EXPERIMENT_STATUS_FAIL';
// deploy experiment fail
const CREATE_DEPLOYMENT_FAIL = 'CREATE_DEPLOYMENT_FAIL';

// EXPORT
export default {
  // REQUEST
  CREATE_EXPERIMENT_RUN_REQUEST,
  GET_TRAIN_EXPERIMENT_STATUS_REQUEST,
  CREATE_DEPLOYMENT_REQUEST,

  // SUCCESS
  CREATE_EXPERIMENT_RUN_SUCCESS,
  GET_TRAIN_EXPERIMENT_STATUS_SUCCESS,
  CREATE_DEPLOYMENT_SUCCESS,

  // FAIL
  CREATE_EXPERIMENT_RUN_FAIL,
  GET_TRAIN_EXPERIMENT_STATUS_FAIL,
  CREATE_DEPLOYMENT_FAIL,
};
