// ACTION TYPES
// REQUEST
// train experiment request
const TRAIN_EXPERIMENT_REQUEST = 'TRAIN_EXPERIMENT_REQUEST';
// get train experiment status request
const GET_TRAIN_EXPERIMENT_STATUS_REQUEST = 'TRAIN_EXPERIMENT_REQUEST';

// SUCCESS
// train experiment success
const TRAIN_EXPERIMENT_SUCCESS = 'TRAIN_EXPERIMENT_SUCCESS';
// get train experiment status success
const GET_TRAIN_EXPERIMENT_STATUS_SUCCESS = 'TRAIN_EXPERIMENT_SUCCESS';

// FAIL
// train experiment fail
const TRAIN_EXPERIMENT_FAIL = 'TRAIN_EXPERIMENT_FAIL';
// get train experiment status fail
const GET_TRAIN_EXPERIMENT_STATUS_FAIL = 'TRAIN_EXPERIMENT_FAIL';

// EXPORT
export default {
  // REQUEST
  TRAIN_EXPERIMENT_REQUEST,
  GET_TRAIN_EXPERIMENT_STATUS_REQUEST,

  // SUCCESS
  TRAIN_EXPERIMENT_SUCCESS,
  GET_TRAIN_EXPERIMENT_STATUS_SUCCESS,

  // FAIL
  TRAIN_EXPERIMENT_FAIL,
  GET_TRAIN_EXPERIMENT_STATUS_FAIL,
};
