// JUPYTER LAB
const JUPYTER_LAB_HEALTHY = 'JUPYTER_LAB_HEALTHY';
const JUPYTER_LAB_UNHEALTHY = 'JUPYTER_LAB_UNHEALTHY';

export default {
  // JUPYTER LAB
  JUPYTER_LAB_HEALTHY,
  JUPYTER_LAB_UNHEALTHY,
};
