// ACTION TYPES
// REQUEST
// fetch components request
const FETCH_COMPONENTS_REQUEST = 'FETCH_COMPONENTS_REQUEST';

// SUCCESS
// fetch components success
const FETCH_COMPONENTS_SUCCESS = 'FETCH_COMPONENTS_SUCCESS';

// FAIL
// fetch components fail
const FETCH_COMPONENTS_FAIL = 'FETCH_COMPONENTS_FAIL';

// EXPORT
export default {
  // REQUEST
  FETCH_COMPONENTS_REQUEST,

  // SUCCESS
  FETCH_COMPONENTS_SUCCESS,

  // FAIL
  FETCH_COMPONENTS_FAIL,
};
