export const MARKETPLACE_LOCAL_STORAGE_KEYS = {
  MARKETPLACE_LIST_ORDER: 'MARKETPLACE_LIST_ORDER',
  MARKETPLACE_LIST_TYPE: 'MARKETPLACE_LIST_TYPE',
};

export const MARKETPLACE_LIST_ORDER = {
  NEWER: 'NEWER',
  OLDER: 'OLDER',
};

export const MARKETPLACE_LIST_TYPE = {
  LIST: 'LIST',
  GRID: 'GRID',
};
