// ACTION TYPES
// REQUEST
// fetch project request
const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
// edit project name request
const EDIT_PROJECT_NAME_REQUEST = 'EDIT_PROJECT_NAME_REQUEST';
// create project request
const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
// delete project request
const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
// edit project request
const EDIT_PROJECT_REQUEST = 'EDIT_PROJECT_REQUEST';

// SUCCESS
// fetch project success
const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';
// edit project name success
const EDIT_PROJECT_NAME_SUCCESS = 'EDIT_PROJECT_NAME_SUCCESS';
// create project success
const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
// delete project success
const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';

// FAIL
// fetch project fail
const FETCH_PROJECT_FAIL = 'FETCH_PROJECT_FAIL';
// edit project name fail
const EDIT_PROJECT_NAME_FAIL = 'EDIT_PROJECT_NAME_FAIL';
// create project fail
const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';
// delete project fail
const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';

// EXPORT
export default {
  // REQUEST
  FETCH_PROJECT_REQUEST,
  EDIT_PROJECT_NAME_REQUEST,
  CREATE_PROJECT_REQUEST,
  DELETE_PROJECT_REQUEST,

  // SUCCESS
  FETCH_PROJECT_SUCCESS,
  EDIT_PROJECT_NAME_SUCCESS,
  CREATE_PROJECT_SUCCESS,
  DELETE_PROJECT_SUCCESS,

  // FAIL
  FETCH_PROJECT_FAIL,
  EDIT_PROJECT_NAME_FAIL,
  CREATE_PROJECT_FAIL,
  DELETE_PROJECT_FAIL,
};
