version: '3'

services:
  platiagro-web-ui-dev:
    image: node:lts

    volumes:
      - ../:/web-ui:cached

    user: ${UID:-1000}:${GID:-1000}

    command: /bin/sh -c "while sleep 1000; do :; done"
