// ACTION TYPES
const FETCH_PAGINATED_PROJECTS = 'FETCH_PAGINATED_PROJECTS';
const FETCH_PROJECTS = 'FETCH_PROJECTS';
const SELECTED_PROJECTS = 'SELECTED_PROJECTS';

// EXPORT
export default {
  FETCH_PAGINATED_PROJECTS,
  FETCH_PROJECTS,
  SELECTED_PROJECTS,
};
