// ACTION TYPES
// fetch projects request
const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';

// fetch projects success
const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';

// fetch projects fail
const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';

// EXPORT
export default {
  FETCH_PROJECTS_REQUEST,
  FETCH_PROJECTS_SUCCESS,
  FETCH_PROJECTS_FAIL,
};
