// ACTION TYPES
// REQUEST
const FETCH_MONITORINGS_REQUEST = 'FETCH_MONITORINGS_REQUEST';
const CREATE_MONITORINGS_REQUEST = 'CREATE_MONITORINGS_REQUEST';
const UPDATE_MONITORINGS_REQUEST = 'UPDATE_MONITORINGS_REQUEST';
const DELETE_MONITORINGS_REQUEST = 'DELETE_MONITORINGS_REQUEST';

// SUCCESS
const GET_MONITORINGS_SUCCESS = 'GET_MONITORINGS_SUCCESS';
const CREATE_MONITORINGS_SUCCESS = 'CREATE_MONITORINGS_SUCCESS';
const UPDATE_MONITORINGS_SUCCESS = 'UPDATE_MONITORINGS_SUCCESS';
const DELETE_MONITORINGS_SUCCESS = 'DELETE_MONITORINGS_SUCCESS';

// FAIL
const GET_MONITORINGS_FAIL = 'GET_MONITORINGS_FAIL';
const CREATE_MONITORINGS_FAIL = 'CREATE_MONITORINGS_FAIL';
const UPDATE_MONITORINGS_FAIL = 'UPDATE_MONITORINGS_FAIL';
const DELETE_MONITORINGS_FAIL = 'DELETE_MONITORINGS_FAIL';

export default {
  FETCH_MONITORINGS_REQUEST,
  CREATE_MONITORINGS_REQUEST,
  UPDATE_MONITORINGS_REQUEST,
  DELETE_MONITORINGS_REQUEST,

  GET_MONITORINGS_SUCCESS,
  CREATE_MONITORINGS_SUCCESS,
  UPDATE_MONITORINGS_SUCCESS,
  DELETE_MONITORINGS_SUCCESS,

  GET_MONITORINGS_FAIL,
  CREATE_MONITORINGS_FAIL,
  UPDATE_MONITORINGS_FAIL,
  DELETE_MONITORINGS_FAIL,
};
