// ACTION TYPES
// REQUEST
const GET_MONITORING_REQUEST = 'GET_MONITORING_REQUEST';
const CREATE_MONITORING_REQUEST = 'CREATE_MONITORING_REQUEST';
const UPDATE_MONITORING_REQUEST = 'UPDATE_MONITORING_REQUEST';
const DELETE_MONITORING_REQUEST = 'DELETE_MONITORING_REQUEST';

// SUCCESS
const GET_MONITORING_SUCCESS = 'GET_MONITORING_SUCCESS';
const CREATE_MONITORING_SUCCESS = 'CREATE_MONITORING_SUCCESS';
const UPDATE_MONITORING_SUCCESS = 'UPDATE_MONITORING_SUCCESS';
const DELETE_MONITORING_SUCCESS = 'DELETE_MONITORING_SUCCESS';

// FAIL
const GET_MONITORING_FAIL = 'GET_MONITORING_FAIL';
const CREATE_MONITORING_FAIL = 'CREATE_MONITORING_FAIL';
const UPDATE_MONITORING_FAIL = 'UPDATE_MONITORING_FAIL';
const DELETE_MONITORING_FAIL = 'DELETE_MONITORING_FAIL';

export default {
  GET_MONITORING_REQUEST,
  CREATE_MONITORING_REQUEST,
  UPDATE_MONITORING_REQUEST,
  DELETE_MONITORING_REQUEST,

  GET_MONITORING_SUCCESS,
  CREATE_MONITORING_SUCCESS,
  UPDATE_MONITORING_SUCCESS,
  DELETE_MONITORING_SUCCESS,

  GET_MONITORING_FAIL,
  CREATE_MONITORING_FAIL,
  UPDATE_MONITORING_FAIL,
  DELETE_MONITORING_FAIL,
};
