const FETCH_MONITORINGS_REQUEST = 'FETCH_MONITORINGS_REQUEST';
const CREATE_MONITORINGS_REQUEST = 'CREATE_MONITORINGS_REQUEST';
const DELETE_MONITORINGS_REQUEST = 'DELETE_MONITORINGS_REQUEST';

const FETCH_MONITORINGS_SUCCESS = 'FETCH_MONITORINGS_SUCCESS';
const CREATE_MONITORINGS_SUCCESS = 'CREATE_MONITORINGS_SUCCESS';
const DELETE_MONITORINGS_SUCCESS = 'DELETE_MONITORINGS_SUCCESS';

const FETCH_MONITORINGS_FAIL = 'FETCH_MONITORINGS_FAIL';
const CREATE_MONITORINGS_FAIL = 'CREATE_MONITORINGS_FAIL';
const DELETE_MONITORINGS_FAIL = 'DELETE_MONITORINGS_FAIL';


export default {
  FETCH_MONITORINGS_REQUEST,
  CREATE_MONITORINGS_REQUEST,
  DELETE_MONITORINGS_REQUEST,

  FETCH_MONITORINGS_SUCCESS,
  CREATE_MONITORINGS_SUCCESS,
  DELETE_MONITORINGS_SUCCESS,

  FETCH_MONITORINGS_FAIL,
  CREATE_MONITORINGS_FAIL,
  DELETE_MONITORINGS_FAIL,
};
