const GET_EXPERIMENT_LOGS = '@EXPERIMENT_LOGS/GET_EXPERIMENT_LOGS';
const GET_EXPERIMENT_LOGS_FAIL = '@EXPERIMENT_LOGS/GET_EXPERIMENT_LOGS_FAIL';
const GET_EXPERIMENT_LOGS_SUCCESS =
  '@EXPERIMENT_LOGS/GET_EXPERIMENT_LOGS_SUCCESS';

// ! QUANDO O PR DE LOADING FICAR PRONTO ISSO VAI SER REMOVIDO
const SET_IS_LOADING_LOGS = '@EXPERIMENT_LOGS/SET_IS_LOADING_LOGS';

const CLEAR_ALL_EXPERIMENT_LOGS = '@EXPERIMENT_LOGS/CLEAR_ALL_EXPERIMENT_LOGS';

export default {
  GET_EXPERIMENT_LOGS,
  GET_EXPERIMENT_LOGS_FAIL,
  GET_EXPERIMENT_LOGS_SUCCESS,

  SET_IS_LOADING_LOGS,

  CLEAR_ALL_EXPERIMENT_LOGS,
};
