// ACTION TYPES
const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
const ADD_TASK_FAIL = 'ADD_TASK_FAIL';
const CLOSE_TASKS_MODAL = 'CLOSE_TASKS_MODAL';
const DELETE_TASK = 'DELETE_TASK';
const FETCH_TASK = 'FETCH_TASK';
const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL';
const SHOW_EDIT_TASK_MODAL = 'SHOW_EDIT_TASK_MODAL';
const SHOW_NEW_TASK_MODAL = 'SHOW_NEW_TASK_MODAL';

// EXPORT
export default {
  ADD_TASK_SUCCESS,
  ADD_TASK_FAIL,
  CLOSE_TASKS_MODAL,
  DELETE_TASK,
  FETCH_TASK,
  UPDATE_TASK_SUCCESS,
  UPDATE_TASK_FAIL,
  SHOW_EDIT_TASK_MODAL,
  SHOW_NEW_TASK_MODAL,
};
