// ACTION TYPES
const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
const CREATE_TASK_FAIL = 'CREATE_TASK_FAIL';
const CLOSE_TASKS_MODAL = 'CLOSE_TASKS_MODAL';
const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
const FETCH_PAGINATED_TASK = 'FETCH_PAGINATED_TASK';
const FETCH_TASK_REQUEST = 'FETCH_TASK_REQUEST';
const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
const UPDATE_TASK_FAIL = 'UPDATE_TASK_FAIL';
const SHOW_EDIT_TASK_MODAL = 'SHOW_EDIT_TASK_MODAL';
const SHOW_NEW_TASK_MODAL = 'SHOW_NEW_TASK_MODAL';
const COPY_TASK_REQUEST = 'COPY_TASK_REQUEST';
const COPY_TASK_SUCCESS = 'COPY_TASK_SUCCESS';
const COPY_TASK_FAIL = 'COPY_TASK_FAIL';

// EXPORT
export default {
  CREATE_TASK_SUCCESS,
  CREATE_TASK_FAIL,
  CLOSE_TASKS_MODAL,
  DELETE_TASK_SUCCESS,
  FETCH_PAGINATED_TASK,
  FETCH_TASK_REQUEST,
  UPDATE_TASK_SUCCESS,
  UPDATE_TASK_FAIL,
  SHOW_EDIT_TASK_MODAL,
  SHOW_NEW_TASK_MODAL,
  COPY_TASK_REQUEST,
  COPY_TASK_SUCCESS,
  COPY_TASK_FAIL,
};
