const GET_DEPLOYMENT_LOGS = '@DEPLOYMENT_LOGS/GET_DEPLOYMENT_LOGS';
const GET_DEPLOYMENT_LOGS_FAIL = '@DEPLOYMENT_LOGS/GET_DEPLOYMENT_LOGS_FAIL';

const CLEAR_ALL_DEPLOYMENT_LOGS = '@DEPLOYMENT_LOGS/CLEAR_ALL_DEPLOYMENT_LOGS';
const APPEND_DEPLOYMENT_LOG = '@DEPLOYMENT_LOGS/APPEND_DEPLOYMENT_LOG';

export default {
  GET_DEPLOYMENT_LOGS,
  GET_DEPLOYMENT_LOGS_FAIL,
  CLEAR_ALL_DEPLOYMENT_LOGS,
  APPEND_DEPLOYMENT_LOG,
};
