// ACTION TYPES
// REQUEST
const GET_DEPLOYMENT_LOGS_REQUEST = 'GET_DEPLOYMENT_LOGS_REQUEST';
const GET_DEPLOYMENT_LOGS_SUCCESS = 'GET_DEPLOYMENT_LOGS_SUCCESS';
const GET_DEPLOYMENT_LOGS_FAIL = 'GET_DEPLOYMENT_LOGS_FAIL';

// EXPORT
export default {
  // REQUEST
  GET_DEPLOYMENT_LOGS_SUCCESS,
  GET_DEPLOYMENT_LOGS_FAIL,
  GET_DEPLOYMENT_LOGS_REQUEST
};
