// ACTION TYPES
// test implanted experiment inference
const TEST_IMPLANTED_EXPERIMENT_INFERENCE =
  'TEST_IMPLANTED_EXPERIMENT_INFERENCE';

const TEST_IMPLANTED_EXPERIMENT_INFERENCE_FAILS =
  'TEST_IMPLANTED_EXPERIMENT_INFERENCE_FAILS';

// EXPORT
export default {
  TEST_IMPLANTED_EXPERIMENT_INFERENCE,
  TEST_IMPLANTED_EXPERIMENT_INFERENCE_FAILS,
};
