// ACTION TYPES
// test implanted experiment inference
const TEST_IMPLANTED_EXPERIMENT_INFERENCE =
  'TEST_IMPLANTED_EXPERIMENT_INFERENCE';

// EXPORT
export default {
  TEST_IMPLANTED_EXPERIMENT_INFERENCE,
};
