// ACTION TYPES
// fetch experiments flow task
const FETCH_EXPERIMENT_TASKS = 'FETCH_EXPERIMENT_TASKS';
// fetch menu tasks
const FETCH_MENU_TASKS = 'FETCH_MENU_TASKS';
// fetch experiment train status
const FETCH_EXPERIMENT_TRAIN_STATUS = 'FETCH_EXPERIMENT_TRAIN_STATUS';
// add task to experiment
const ADD_EXPERIMENT_TASK = 'ADD_EXPERIMENT_TASK';
// remove task from experiment
const REMOVE_EXPERIMENT_TASK = 'REMOVE_EXPERIMENT_TASK';
// set experiment tasks params
const SET_EXPERIMENT_TASKS_PARAMS = 'SET_EXPERIMENT_TASKS_PARAMS';

// EXPORT
export default {
  FETCH_EXPERIMENT_TASKS,
  FETCH_MENU_TASKS,
  FETCH_EXPERIMENT_TRAIN_STATUS,
  ADD_EXPERIMENT_TASK,
  REMOVE_EXPERIMENT_TASK,
  SET_EXPERIMENT_TASKS_PARAMS,
};
