export const FETCH_TEMPLATES_REQUEST = '@TEMPLATES/FETCH_TEMPLATES_REQUEST';
export const FETCH_TEMPLATES_SUCCESS = '@TEMPLATES/FETCH_TEMPLATES_SUCCESS';
export const FETCH_TEMPLATES_FAIL = '@TEMPLATES/FETCH_TEMPLATES_FAIL';

export const CREATE_TEMPLATE_REQUEST = '@TEMPLATES/CREATE_TEMPLATE_REQUEST';
export const CREATE_TEMPLATE_SUCCESS = '@TEMPLATES/CREATE_TEMPLATE_SUCCESS';
export const CREATE_TEMPLATE_FAIL = '@TEMPLATES/CREATE_TEMPLATE_FAIL';

export const UPDATE_TEMPLATE_REQUEST = '@TEMPLATES/UPDATE_TEMPLATE_REQUEST';
export const UPDATE_TEMPLATE_SUCCESS = '@TEMPLATES/UPDATE_TEMPLATE_SUCCESS';
export const UPDATE_TEMPLATE_FAIL = '@TEMPLATES/UPDATE_TEMPLATE_FAIL';

export const DELETE_TEMPLATE_REQUEST = '@TEMPLATES/DELETE_TEMPLATE_REQUEST';
export const DELETE_TEMPLATE_SUCCESS = '@TEMPLATES/DELETE_TEMPLATE_SUCCESS';
export const DELETE_TEMPLATE_FAIL = '@TEMPLATES/DELETE_TEMPLATE_FAIL';

export const SET_TEMPLATE_REQUEST = '@TEMPLATES/SET_TEMPLATE_REQUEST';
export const SET_TEMPLATE_SUCCESS = '@TEMPLATES/SET_TEMPLATE_SUCCESS';
export const SET_TEMPLATE_FAIL = '@TEMPLATES/SET_TEMPLATE_FAIL';
