// ACTION TYPES
// REQUEST
// fetch templates request
const FETCH_TEMPLATES_REQUEST = 'FETCH_TEMPLATES_REQUEST';
// create template request
const CREATE_TEMPLATE_REQUEST = 'CREATE_TEMPLATE_REQUEST';
// update template request
const UPDATE_TEMPLATE_REQUEST =  'UPDATE_TEMPLATE_REQUEST';
// delete template request
const DELETE_TEMPLATE_REQUEST = 'DELETE_TEMPLATE_REQUEST';
// set template request
const SET_TEMPLATE_REQUEST = 'SET_TEMPLATE_REQUEST';

// SUCCESS
// fetch templates success
const FETCH_TEMPLATES_SUCCESS = 'FETCH_TEMPLATES_SUCCESS';
// create template success
const CREATE_TEMPLATE_SUCCESS = 'CREATE_TEMPLATE_SUCCESS';
// update template success
const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS';
// delete template success
const DELETE_TEMPLATE_SUCCESS = 'DELETE_TEMPLATE_SUCCESS';
// set template success
const SET_TEMPLATE_SUCCESS = 'SET_TEMPLATE_SUCCESS';

// FAIL
// fetch templates fail
const FETCH_TEMPLATES_FAIL = 'FETCH_TEMPLATES_FAIL';
// create template fail
const CREATE_TEMPLATE_FAIL = 'CREATE_TEMPLATE_FAIL';
// update template fail
const UPDATE_TEMPLATE_FAIL = 'UPDATE_TEMPLATE_FAIL';
// delete template fail
const DELETE_TEMPLATE_FAIL = 'DELETE_TEMPLATE_FAIL';
// set template fail
const SET_TEMPLATE_FAIL = 'SET_TEMPLATE_FAIL';

// EXPORT
export default {
  // REQUEST
  FETCH_TEMPLATES_REQUEST,
  CREATE_TEMPLATE_REQUEST,
  UPDATE_TEMPLATE_REQUEST,
  DELETE_TEMPLATE_REQUEST,
  SET_TEMPLATE_REQUEST,

  // SUCCESS
  FETCH_TEMPLATES_SUCCESS,
  CREATE_TEMPLATE_SUCCESS,
  UPDATE_TEMPLATE_SUCCESS,
  DELETE_TEMPLATE_SUCCESS,
  SET_TEMPLATE_SUCCESS,

  // FAIL
  FETCH_TEMPLATES_FAIL,
  CREATE_TEMPLATE_FAIL,
  UPDATE_TEMPLATE_FAIL,
  DELETE_TEMPLATE_FAIL,
  SET_TEMPLATE_FAIL,
};
