// ACTION TYPES
// REQUEST
const FETCH_OPERATORS_REQUEST = 'FETCH_OPERATORS_REQUEST';
const CLEAR_OPERATORS_FEATURE_PARAMETERS_REQUEST =
  'CLEAR_OPERATORS_FEATURE_PARAMETERS_REQUEST';

// SUCCESS
const FETCH_OPERATORS_SUCCESS = 'FETCH_OPERATORS_SUCCESS';
const UPDATE_OPERATOR_DEPENDENCIES = 'UPDATE_OPERATOR_DEPENDENCIES';
const UPDATE_OPERATORS_OPTIONS = 'UPDATE_OPERATORS_OPTIONS';

// FAIL
const FETCH_OPERATORS_FAIL = 'FETCH_OPERATORS_FAIL';

// EXPORT
export default {
  // REQUEST
  FETCH_OPERATORS_REQUEST,
  CLEAR_OPERATORS_FEATURE_PARAMETERS_REQUEST,

  // SUCCESS
  FETCH_OPERATORS_SUCCESS,
  UPDATE_OPERATOR_DEPENDENCIES,
  UPDATE_OPERATORS_OPTIONS,

  // FAIL
  FETCH_OPERATORS_FAIL,
};
