// ACTION TYPES
const FETCH_DEPLOYMENT_OPERATORS_REQUEST = 'FETCH_DEPLOYMENT_OPERATORS_REQUEST';
const FETCH_DEPLOYMENT_OPERATORS_SUCCESS = 'FETCH_DEPLOYMENT_OPERATORS_SUCCESS';
const FETCH_DEPLOYMENT_OPERATORS_FAIL = 'FETCH_DEPLOYMENT_OPERATORS_FAIL';

// EXPORT
export default {
  FETCH_DEPLOYMENT_OPERATORS_REQUEST,
  FETCH_DEPLOYMENT_OPERATORS_SUCCESS,
  FETCH_DEPLOYMENT_OPERATORS_FAIL,
};
