// ACTION TYPES
// fetch implanted experiments
const FETCH_IMPLANTED_EXPERIMENTS = 'FETCH_IMPLANTED_EXPERIMENTS';
// test implanted experiment inference
const TEST_IMPLANTED_EXPERIMENT_INFERENCE =
  'TEST_IMPLANTED_EXPERIMENT_INFERENCE';
// delete implanted experiment
const DELETE_IMPLANTED_EXPERIMENT = 'DELETE_IMPLANTED_EXPERIMENT';

// EXPORT
export default {
  FETCH_IMPLANTED_EXPERIMENTS,
  TEST_IMPLANTED_EXPERIMENT_INFERENCE,
  DELETE_IMPLANTED_EXPERIMENT,
};
