// ACTION TYPES
// fetch implanted experiments
const FETCH_IMPLANTED_EXPERIMENTS = 'FETCH_IMPLANTED_EXPERIMENTS';
// fetch implanted experiments fail
const FETCH_IMPLANTED_EXPERIMENTS_FAIL = 'FETCH_IMPLANTED_EXPERIMENTS_FAIL';
// delete implanted experiment
const DELETE_IMPLANTED_EXPERIMENT = 'DELETE_IMPLANTED_EXPERIMENT';

// EXPORT
export default {
  FETCH_IMPLANTED_EXPERIMENTS,
  DELETE_IMPLANTED_EXPERIMENT,
  FETCH_IMPLANTED_EXPERIMENTS_FAIL,
};
