// ACTION TYPES
const DELETE_IMPLANTED_EXPERIMENT = 'DELETE_IMPLANTED_EXPERIMENT';
const DELETE_IMPLANTED_EXPERIMENT_FAIL = 'DELETE_IMPLANTED_EXPERIMENT_FAIL';
const DELETE_IMPLANTED_EXPERIMENT_REQUEST =
  'DELETE_IMPLANTED_EXPERIMENT_REQUEST';

const FETCH_IMPLANTED_EXPERIMENTS = 'FETCH_IMPLANTED_EXPERIMENTS';
const FETCH_IMPLANTED_EXPERIMENTS_FAIL = 'FETCH_IMPLANTED_EXPERIMENTS_FAIL';
const FETCH_IMPLANTED_EXPERIMENTS_REQUEST =
  'FETCH_IMPLANTED_EXPERIMENTS_REQUEST';

// EXPORT
export default {
  DELETE_IMPLANTED_EXPERIMENT,
  DELETE_IMPLANTED_EXPERIMENT_FAIL,
  DELETE_IMPLANTED_EXPERIMENT_REQUEST,
  FETCH_IMPLANTED_EXPERIMENTS,
  FETCH_IMPLANTED_EXPERIMENTS_FAIL,
  FETCH_IMPLANTED_EXPERIMENTS_REQUEST,
};
