// ACTION TYPES
// NEW PROJECT MODAL
// show new project modal
const SHOW_NEW_PROJECT_MODAL = 'SHOW_NEW_PROJECT_MODAL';

// SHOW USING_DEPLOYMENTS_MODAL
//HIDE USING_DEPLOYMENTS_MODAL
const SHOW_USING_DEPLOYMENTS_MODAL = 'SHOW_USING_DEPLOYMENTS_MODAL';
const HIDE_USING_DEPLOYMENTS_MODAL = 'HIDE_USING_DEPLOYMENTS_MODAL';

// show edit project modal
const SHOW_EDIT_PROJECT_MODAL = 'SHOW_EDIT_PROJECT_MODAL';
// hide new project modal
const HIDE_NEW_PROJECT_MODAL = 'HIDE_NEW_PROJECT_MODAL';

// NEW EXPERIMENT MODAL
// show new experiment modal
const SHOW_NEW_EXPERIMENT_MODAL = 'SHOW_NEW_EXPERIMENT_MODAL';
// hide new experiment modal
const HIDE_NEW_EXPERIMENT_MODAL = 'HIDE_NEW_EXPERIMENT_MODAL';

// NEW TEMPLATE MODAL
// show new template modal
const SHOW_NEW_TEMPLATE_MODAL = 'SHOW_NEW_TEMPLATE_MODAL';
// hide new template modal
const HIDE_NEW_TEMPLATE_MODAL = 'HIDE_NEW_TEMPLATE_MODAL';

// DRAWER
// show drawer
const SHOW_DRAWER = 'SHOW_DRAWER';
// hide drawer
const HIDE_DRAWER = 'HIDE_DRAWER';

// TASKS TABLE
// loading data
const TASKS_TABLE_LOADING_DATA = 'TASKS_TABLE_LOADING_DATA';
// data loaded
const TASKS_TABLE_DATA_LOADED = 'TASKS_TABLE_DATA_LOADED';

// PROJECTS TABLE
// loading data
const PROJECTS_TABLE_LOADING_DATA = 'PROJECTS_TABLE_LOADING_DATA';
// data loaded
const PROJECTS_TABLE_DATA_LOADED = 'PROJECTS_TABLE_DATA_LOADED';

// PROJECT NAME
// loading data
const PROJECT_NAME_LOADING_DATA = 'PROJECT_NAME_LOADING_DATA';
// data loaded
const PROJECT_NAME_DATA_LOADED = 'PROJECT_NAME_DATA_LOADED';

// COMPONENTS MENU
// loading data
const COMPONENTS_MENU_LOADING_DATA = 'COMPONENTS_MENU_LOADING_DATA';
// data loaded
const COMPONENTS_MENU_DATA_LOADED = 'COMPONENTS_MENU_DATA_LOADED';

// EXPERIMENTS TABS
// loading data
const EXPERIMENTS_TABS_LOADING_DATA = 'EXPERIMENTS_TABS_LOADING_DATA';
// data loaded
const EXPERIMENTS_TABS_DATA_LOADED = 'EXPERIMENTS_TABS_DATA_LOADED';

// EXPERIMENT NAME
// loading data
const EXPERIMENT_NAME_LOADING_DATA = 'EXPERIMENT_NAME_LOADING_DATA';
// data loaded
const EXPERIMENT_NAME_DATA_LOADED = 'EXPERIMENT_NAME_DATA_LOADED';

// EXPERIMENT OPERATORS
// loading data
const EXPERIMENT_OPERATORS_LOADING_DATA = 'EXPERIMENT_OPERATORS_LOADING_DATA';
// data loaded
const EXPERIMENT_OPERATORS_DATA_LOADED = 'EXPERIMENT_OPERATORS_DATA_LOADED';

// DATASET OPERATOR
// loading data
const DATASET_OPERATOR_LOADING_DATA = 'DATASET_OPERATOR_LOADING_DATA';
// data loaded
const DATASET_OPERATOR_DATA_LOADED = 'DATASET_OPERATOR_DATA_LOADED';

// OPERATOR PARAMETER
// loading data
const OPERATOR_PARAMETER_LOADING_DATA = 'OPERATOR_PARAMETER_LOADING_DATA';
// data loaded
const OPERATOR_PARAMETER_DATA_LOADED = 'OPERATOR_PARAMETER_DATA_LOADED';

// OPERATOR RESULTS
// loading data
const OPERATOR_RESULTS_LOADING_DATA = 'OPERATOR_RESULTS_LOADING_DATA';
// data loaded
const OPERATOR_RESULTS_DATA_LOADED = 'OPERATOR_RESULTS_DATA_LOADED';

// TEMPLATE
// loading data (used in save template)
const TEMPLATE_LOADING_DATA = 'TEMPLATE_LOADING_DATA';
// data loaded (used in save template)
const TEMPLATE_DATA_LOADED = 'TEMPLATE_DATA_LOADED';

// EXPERIMENT TARGET
// loading data
const EXPERIMENT_TARGET_LOADING_DATA = 'EXPERIMENT_TARGET_LOADING_DATA';
// data loaded
const EXPERIMENT_TARGET_DATA_LOADED = 'EXPERIMENT_TARGET_DATA_LOADED';

// IMPLANTED EXPERIMENTS
// loading data
const IMPLANTED_EXPERIMENTS_LOADING_DATA = 'IMPLANTED_EXPERIMENTS_LOADING_DATA';
// data loaded
const IMPLANTED_EXPERIMENTS_DATA_LOADED = 'IMPLANTED_EXPERIMENTS_DATA_LOADED';
// EXPERIMENT TRAINING
// loading data
const EXPERIMENT_TRAINING_LOADING_DATA = 'EXPERIMENT_TRAINING_LOADING_DATA';
// data loaded
const EXPERIMENT_TRAINING_DATA_LOADED = 'EXPERIMENT_TRAINING_DATA_LOADED';

const SHOW_EXPERIMENT_INFERENCE_MODAL = 'SHOW_EXPERIMENT_INFERENCE_MODAL';

const HIDE_EXPERIMENT_INFERENCE_MODAL = 'HIDE_EXPERIMENT_INFERENCE_MODAL';

// loading data
const OPERATOR_METRICS_LOADING_DATA = 'OPERATOR_METRICS_LOADING_DATA';
// data loaded
const OPERATOR_METRICS_DATA_LOADED = 'OPERATOR_METRICS_DATA_LOADED';

// EXPORT
export default {
  // NEW PROJECT MODAL
  SHOW_NEW_PROJECT_MODAL,
  HIDE_NEW_PROJECT_MODAL,
  SHOW_EDIT_PROJECT_MODAL,

  // USING_DEPLOYMENTS_MODAL
  SHOW_USING_DEPLOYMENTS_MODAL,
  HIDE_USING_DEPLOYMENTS_MODAL,

  // NEW EXPERIMENT MODAL
  SHOW_NEW_EXPERIMENT_MODAL,
  HIDE_NEW_EXPERIMENT_MODAL,

  // NEW TEMPLATE MODAL
  SHOW_NEW_TEMPLATE_MODAL,
  HIDE_NEW_TEMPLATE_MODAL,

  // DRAWER
  SHOW_DRAWER,
  HIDE_DRAWER,

  // TASKS TABLE
  TASKS_TABLE_LOADING_DATA,
  TASKS_TABLE_DATA_LOADED,

  // PROJECTS TABLE
  PROJECTS_TABLE_LOADING_DATA,
  PROJECTS_TABLE_DATA_LOADED,

  // PROJECT NAME
  PROJECT_NAME_LOADING_DATA,
  PROJECT_NAME_DATA_LOADED,

  // COMPONENT MENU
  COMPONENTS_MENU_LOADING_DATA,
  COMPONENTS_MENU_DATA_LOADED,

  // EXPERIMENTS TABS
  EXPERIMENTS_TABS_LOADING_DATA,
  EXPERIMENTS_TABS_DATA_LOADED,

  // EXPERIMENT NAME
  EXPERIMENT_NAME_LOADING_DATA,
  EXPERIMENT_NAME_DATA_LOADED,

  // EXPERIMENT OPERATORS
  EXPERIMENT_OPERATORS_LOADING_DATA,
  EXPERIMENT_OPERATORS_DATA_LOADED,

  // DATASET OPERATOR
  DATASET_OPERATOR_LOADING_DATA,
  DATASET_OPERATOR_DATA_LOADED,

  // OPERATOR PARAMETER
  OPERATOR_PARAMETER_LOADING_DATA,
  OPERATOR_PARAMETER_DATA_LOADED,

  // OPERATOR RESULTS
  OPERATOR_RESULTS_LOADING_DATA,
  OPERATOR_RESULTS_DATA_LOADED,

  // TEMPLATE
  TEMPLATE_LOADING_DATA,
  TEMPLATE_DATA_LOADED,

  // EXPERIMENT TARGET
  EXPERIMENT_TARGET_LOADING_DATA,
  EXPERIMENT_TARGET_DATA_LOADED,

  // IMPLANTED EXPERIMENT
  IMPLANTED_EXPERIMENTS_LOADING_DATA,
  IMPLANTED_EXPERIMENTS_DATA_LOADED,
  // EXPERIMENT TRAINING
  EXPERIMENT_TRAINING_LOADING_DATA,
  EXPERIMENT_TRAINING_DATA_LOADED,

  // IMPLANTED EXPERIMENT MODAL
  SHOW_EXPERIMENT_INFERENCE_MODAL,
  HIDE_EXPERIMENT_INFERENCE_MODAL,

  OPERATOR_METRICS_LOADING_DATA,
  OPERATOR_METRICS_DATA_LOADED,
};
